### ISSUE TITLE
separate train and test parquet files

### ISSUE THREAD

**Issue by tarakc02** [ppact/extraction#26]
Ayyub's code for model training relies on separate train.parquet and test.parquet files. We could do the filtering at that point, but I think outputting separate data frames simplifies everything that happens downstream. You shouldn't have to change anything else about the import step or the way it's structured (I especially want to make sure we keep the summaries that get output in the log), just output "output/train.parquet" and "output/test.parquet" instead of or in addition to "output/train-test.parquet"

**Comment by baileyb0t** [comment]
Makes sense! I'll write them as separate files.

Since each set has distinct article_ids, it should be easy to load both and rebuild "output/train-test.parquet" using [pd.concat()](https://pandas.pydata.org/docs/reference/api/pandas.concat.html). I think it's safe to just output the 2 files unless we want to keep all filtering/cleaning/manipulating code outside of modeling tasks as a rule, which also makes sense!

**Comment by ayyubibrahimi** [comment]
Works perfectly. Thanks!
