### ISSUE TITLE
task for duplicate and near-duplicate recognition

### ISSUE THREAD

**Issue by tarakc02** [ppact/extraction#34]
@baileyb0t had previously recognized the issue of duplicate article content with different article ids. We discussed the issue at today's meeting -- still figuring out how to best handle it on the front end, but we decided a useful next step here is to be able to identify the instances. We want a task that can output groups of article ids that all have identical or nearly identical content. As a first step, we can implement this task based on identical content, and then modify it to also be able to detect nearly-identical content.

**Comment by baileyb0t** [comment]
@tarakc02 I added a script to import/src that writes a list of grouped article_ids as "output/dup_groups.yml". It is part of a pull request that needs to be reviewed, but once the linked pull request is closed you should be able to run make and see the results! 

The short answer is there are 651 groups of article_ids with exactly duplicate content in news.parquet, and about 1300 article_ids represented in that collection.  Since the news data is generated with one unique article_id in each row, these should all be unique ids.

Most groups contain just 2 article_ids, but here is one with several:
  - 23174
  - 20541
  - 19075
  - 17570
  - 28958
  - 13415
  - 23914
  - 16163
  - 12274
  - 25380
  - 26870

**Comment by baileyb0t** [comment]
This got closed as a result of the linked pull request getting merged to the main branch, but the 'near duplicate' portion of the issue has not been resolved. Reopening.
